# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml

- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v4.3.20'
  hooks:
  - id: isort
    additional_dependencies: [ "toml" ]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy

- repo: https://github.com/jazzband/pip-tools
  rev: 6.6.2
  hooks:
    - id: pip-compile
      name: pip-compile setup.py
      files: ^(setup\.py|requirements\.txt)$