version: '2.1'
services:
  service:
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      DEBUG: "true"
      SQLALCHEMY_DATABASE_URI: "postgres://raduser:radpass@postgres:5432/rad_task"
  postgres:
    image: postgres:9.6.24-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: raduser
      POSTGRES_PASSWORD: radpass
      POSTGRES_DB: rad_task
